// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: submodule/product_service/product_discount.proto

package product_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProductDiscount represents a discount applied to a specific product.
type ProductDiscount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId  string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DiscountId string                 `protobuf:"bytes,3,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ProductDiscount) Reset() {
	*x = ProductDiscount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductDiscount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDiscount) ProtoMessage() {}

func (x *ProductDiscount) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDiscount.ProtoReflect.Descriptor instead.
func (*ProductDiscount) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{0}
}

func (x *ProductDiscount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductDiscount) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductDiscount) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

func (x *ProductDiscount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductDiscount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateProductDiscountRequest represents a request to create a new product discount.
type CreateProductDiscountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDiscount *ProductDiscount `protobuf:"bytes,1,opt,name=product_discount,json=productDiscount,proto3" json:"product_discount,omitempty"`
}

func (x *CreateProductDiscountRequest) Reset() {
	*x = CreateProductDiscountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProductDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductDiscountRequest) ProtoMessage() {}

func (x *CreateProductDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductDiscountRequest.ProtoReflect.Descriptor instead.
func (*CreateProductDiscountRequest) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductDiscountRequest) GetProductDiscount() *ProductDiscount {
	if x != nil {
		return x.ProductDiscount
	}
	return nil
}

// CreateProductDiscountResponse represents a response to a CreateProductDiscountRequest.
type CreateProductDiscountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDiscount *ProductDiscount `protobuf:"bytes,1,opt,name=product_discount,json=productDiscount,proto3" json:"product_discount,omitempty"`
}

func (x *CreateProductDiscountResponse) Reset() {
	*x = CreateProductDiscountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProductDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductDiscountResponse) ProtoMessage() {}

func (x *CreateProductDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductDiscountResponse.ProtoReflect.Descriptor instead.
func (*CreateProductDiscountResponse) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductDiscountResponse) GetProductDiscount() *ProductDiscount {
	if x != nil {
		return x.ProductDiscount
	}
	return nil
}

// GetProductDiscountRequest represents a request to get a product discount by ID.
type GetProductDiscountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProductDiscountRequest) Reset() {
	*x = GetProductDiscountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDiscountRequest) ProtoMessage() {}

func (x *GetProductDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDiscountRequest.ProtoReflect.Descriptor instead.
func (*GetProductDiscountRequest) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductDiscountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetProductDiscountResponse represents a response to a GetProductDiscountRequest.
type GetProductDiscountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDiscount *ProductDiscount `protobuf:"bytes,1,opt,name=product_discount,json=productDiscount,proto3" json:"product_discount,omitempty"`
}

func (x *GetProductDiscountResponse) Reset() {
	*x = GetProductDiscountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDiscountResponse) ProtoMessage() {}

func (x *GetProductDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDiscountResponse.ProtoReflect.Descriptor instead.
func (*GetProductDiscountResponse) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductDiscountResponse) GetProductDiscount() *ProductDiscount {
	if x != nil {
		return x.ProductDiscount
	}
	return nil
}

// UpdateProductDiscountRequest represents a request to update an existing product discount.
type UpdateProductDiscountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDiscount *ProductDiscount `protobuf:"bytes,1,opt,name=product_discount,json=productDiscount,proto3" json:"product_discount,omitempty"`
}

func (x *UpdateProductDiscountRequest) Reset() {
	*x = UpdateProductDiscountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProductDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductDiscountRequest) ProtoMessage() {}

func (x *UpdateProductDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductDiscountRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductDiscountRequest) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductDiscountRequest) GetProductDiscount() *ProductDiscount {
	if x != nil {
		return x.ProductDiscount
	}
	return nil
}

// UpdateProductDiscountResponse represents a response to an UpdateProductDiscountRequest.
type UpdateProductDiscountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDiscount *ProductDiscount `protobuf:"bytes,1,opt,name=product_discount,json=productDiscount,proto3" json:"product_discount,omitempty"`
}

func (x *UpdateProductDiscountResponse) Reset() {
	*x = UpdateProductDiscountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProductDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductDiscountResponse) ProtoMessage() {}

func (x *UpdateProductDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductDiscountResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductDiscountResponse) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductDiscountResponse) GetProductDiscount() *ProductDiscount {
	if x != nil {
		return x.ProductDiscount
	}
	return nil
}

// DeleteProductDiscountRequest represents a request to delete a product discount by ID.
type DeleteProductDiscountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProductDiscountRequest) Reset() {
	*x = DeleteProductDiscountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProductDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductDiscountRequest) ProtoMessage() {}

func (x *DeleteProductDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductDiscountRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductDiscountRequest) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductDiscountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteProductDiscountResponse represents a response to a DeleteProductDiscountRequest.
type DeleteProductDiscountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Success message
}

func (x *DeleteProductDiscountResponse) Reset() {
	*x = DeleteProductDiscountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProductDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductDiscountResponse) ProtoMessage() {}

func (x *DeleteProductDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductDiscountResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductDiscountResponse) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProductDiscountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListProductDiscountsRequest represents a request to list product discounts.
type ListProductDiscountsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit      int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ProductId  string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`    // Add product_id filter
	DiscountId string `protobuf:"bytes,4,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"` // Add discount_id filter
}

func (x *ListProductDiscountsRequest) Reset() {
	*x = ListProductDiscountsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProductDiscountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductDiscountsRequest) ProtoMessage() {}

func (x *ListProductDiscountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductDiscountsRequest.ProtoReflect.Descriptor instead.
func (*ListProductDiscountsRequest) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductDiscountsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductDiscountsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductDiscountsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ListProductDiscountsRequest) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

// ListProductDiscountsResponse represents a response to a ListProductDiscountsRequest.
type ListProductDiscountsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDiscounts []*ProductDiscount `protobuf:"bytes,1,rep,name=product_discounts,json=productDiscounts,proto3" json:"product_discounts,omitempty"`
	Total            int32              `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListProductDiscountsResponse) Reset() {
	*x = ListProductDiscountsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_product_service_product_discount_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProductDiscountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductDiscountsResponse) ProtoMessage() {}

func (x *ListProductDiscountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_product_service_product_discount_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductDiscountsResponse.ProtoReflect.Descriptor instead.
func (*ListProductDiscountsResponse) Descriptor() ([]byte, []int) {
	return file_submodule_product_service_product_discount_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductDiscountsResponse) GetProductDiscounts() []*ProductDiscount {
	if x != nil {
		return x.ProductDiscounts
	}
	return nil
}

func (x *ListProductDiscountsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_submodule_product_service_product_discount_proto protoreflect.FileDescriptor

var file_submodule_product_service_product_discount_proto_rawDesc = []byte{
	0x0a, 0x30, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x6b,
	0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4b,
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6c, 0x0a, 0x1d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x6b, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x4b, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6c,
	0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4b, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x1c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x1d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x83, 0x01, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4d, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xe4, 0x04, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x76, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2d, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x76, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x76, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2d, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x12, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1b,
	0x5a, 0x19, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_submodule_product_service_product_discount_proto_rawDescOnce sync.Once
	file_submodule_product_service_product_discount_proto_rawDescData = file_submodule_product_service_product_discount_proto_rawDesc
)

func file_submodule_product_service_product_discount_proto_rawDescGZIP() []byte {
	file_submodule_product_service_product_discount_proto_rawDescOnce.Do(func() {
		file_submodule_product_service_product_discount_proto_rawDescData = protoimpl.X.CompressGZIP(file_submodule_product_service_product_discount_proto_rawDescData)
	})
	return file_submodule_product_service_product_discount_proto_rawDescData
}

var file_submodule_product_service_product_discount_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_submodule_product_service_product_discount_proto_goTypes = []any{
	(*ProductDiscount)(nil),               // 0: product_service.ProductDiscount
	(*CreateProductDiscountRequest)(nil),  // 1: product_service.CreateProductDiscountRequest
	(*CreateProductDiscountResponse)(nil), // 2: product_service.CreateProductDiscountResponse
	(*GetProductDiscountRequest)(nil),     // 3: product_service.GetProductDiscountRequest
	(*GetProductDiscountResponse)(nil),    // 4: product_service.GetProductDiscountResponse
	(*UpdateProductDiscountRequest)(nil),  // 5: product_service.UpdateProductDiscountRequest
	(*UpdateProductDiscountResponse)(nil), // 6: product_service.UpdateProductDiscountResponse
	(*DeleteProductDiscountRequest)(nil),  // 7: product_service.DeleteProductDiscountRequest
	(*DeleteProductDiscountResponse)(nil), // 8: product_service.DeleteProductDiscountResponse
	(*ListProductDiscountsRequest)(nil),   // 9: product_service.ListProductDiscountsRequest
	(*ListProductDiscountsResponse)(nil),  // 10: product_service.ListProductDiscountsResponse
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
}
var file_submodule_product_service_product_discount_proto_depIdxs = []int32{
	11, // 0: product_service.ProductDiscount.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: product_service.ProductDiscount.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: product_service.CreateProductDiscountRequest.product_discount:type_name -> product_service.ProductDiscount
	0,  // 3: product_service.CreateProductDiscountResponse.product_discount:type_name -> product_service.ProductDiscount
	0,  // 4: product_service.GetProductDiscountResponse.product_discount:type_name -> product_service.ProductDiscount
	0,  // 5: product_service.UpdateProductDiscountRequest.product_discount:type_name -> product_service.ProductDiscount
	0,  // 6: product_service.UpdateProductDiscountResponse.product_discount:type_name -> product_service.ProductDiscount
	0,  // 7: product_service.ListProductDiscountsResponse.product_discounts:type_name -> product_service.ProductDiscount
	1,  // 8: product_service.ProductDiscountService.CreateProductDiscount:input_type -> product_service.CreateProductDiscountRequest
	3,  // 9: product_service.ProductDiscountService.GetProductDiscount:input_type -> product_service.GetProductDiscountRequest
	5,  // 10: product_service.ProductDiscountService.UpdateProductDiscount:input_type -> product_service.UpdateProductDiscountRequest
	7,  // 11: product_service.ProductDiscountService.DeleteProductDiscount:input_type -> product_service.DeleteProductDiscountRequest
	9,  // 12: product_service.ProductDiscountService.ListProductDiscounts:input_type -> product_service.ListProductDiscountsRequest
	2,  // 13: product_service.ProductDiscountService.CreateProductDiscount:output_type -> product_service.CreateProductDiscountResponse
	4,  // 14: product_service.ProductDiscountService.GetProductDiscount:output_type -> product_service.GetProductDiscountResponse
	6,  // 15: product_service.ProductDiscountService.UpdateProductDiscount:output_type -> product_service.UpdateProductDiscountResponse
	8,  // 16: product_service.ProductDiscountService.DeleteProductDiscount:output_type -> product_service.DeleteProductDiscountResponse
	10, // 17: product_service.ProductDiscountService.ListProductDiscounts:output_type -> product_service.ListProductDiscountsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_submodule_product_service_product_discount_proto_init() }
func file_submodule_product_service_product_discount_proto_init() {
	if File_submodule_product_service_product_discount_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_submodule_product_service_product_discount_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProductDiscount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateProductDiscountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateProductDiscountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetProductDiscountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetProductDiscountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateProductDiscountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateProductDiscountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteProductDiscountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteProductDiscountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListProductDiscountsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_product_service_product_discount_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListProductDiscountsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submodule_product_service_product_discount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submodule_product_service_product_discount_proto_goTypes,
		DependencyIndexes: file_submodule_product_service_product_discount_proto_depIdxs,
		MessageInfos:      file_submodule_product_service_product_discount_proto_msgTypes,
	}.Build()
	File_submodule_product_service_product_discount_proto = out.File
	file_submodule_product_service_product_discount_proto_rawDesc = nil
	file_submodule_product_service_product_discount_proto_goTypes = nil
	file_submodule_product_service_product_discount_proto_depIdxs = nil
}
